import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import "../public/css/theme.css";
import Footer from "./components/Footer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="/js/theme.js" />
      <Script src="/vendors/@popperjs/popper.min.js" />
      <Script src="/vendors/bootstrap/bootstrap.min.js" />
      <Script src="/vendors/is/is.min.js" />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Nav />
        {children}
        <Footer />
        <Script src="/js/theme.js" />
        <Script src="/vendors/@popperjs/popper.min.js" />
        <Script src="/vendors/bootstrap/bootstrap.min.js" />
        <Script src="/vendors/is/is.min.js" />
      </body>
    </html>
  );
}
